name: Publish Main
on:
  push:
    branches:
      - main

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest

    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(feat|fix|docs|style|refactor|test|chore)(\([A-Za-z\-]+\))?:.+'
          error: 'Commit messages must begin with a valid commit type, with optional scope.'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Lint Markdown
        run: npm run lint:md

      - name: Lint CSS
        run: npm run lint:css

      - name: Lint JS
        run: npm run lint:js
      
      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          printf "todo"
